# Generated by Django 2.2.2 on 2019-12-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=222)),
                ('last_name', models.CharField(max_length=222)),
                ('email', models.CharField(max_length=222)),
                ('address', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school', models.CharField(max_length=222)),
                ('intermediate', models.CharField(max_length=22)),
                ('bachelor', models.CharField(max_length=22)),
                ('master', models.CharField(max_length=22)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='crud.Employee')),
            ],
        ),
    ]
